config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    root to: "users#index"
  end

  devise_for :users

  authenticated :user do
    root to: "home#index", as: :user_root
  end

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string
#  last_name              :string
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  role                   :string           default("user")
#  sign_in_count          :integer          default(0), not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  extend Enumerize
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable, :trackable

  # Enums
  enumerize :role, in: [:user, :admin], default: :user, predicates: true, scope: true

  # Validations
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this
# `Administrate::ApplicationController`, making it the ideal place to put
# authentication logic or other before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin

    def authenticate_admin
      redirect_to "/", alert: "Not authorized." unless user_signed_in? && current_user.admin?
    end

    # Whether the named action route exists for the resource class.
    #
    # @param resource [Class, String, Symbol] A class of resources, or the name
    #   of a class of resources.
    # @param action_name [String, Symbol] The name of an action that might be
    #   possible to perform on a resource or resource class.
    # @return [Boolean] `true` if a route exists for the resource class and the
    #   action. `false` otherwise.
    def existing_action?(resource, action_name)
      routes.include?([resource.to_s.underscore.pluralize, action_name.to_s])
    end
    helper_method :existing_action?
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_controller?(names)
    return false if params[:controller].blank?
    names.include?(params[:controller])
  end

  helper_method :current_controller?
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "static"

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_svg(name, options = {})
    options[:title] ||= name.underscore.humanize
    options[:aria] = true
    options[:nocomment] = true
    options[:class] = options.fetch(:styles, "fill-current text-gray-500")

    filename = "#{name}.svg"
    inline_svg_tag(filename, options)
  end
end

app/views/home/index.html.erb
<!-- Hero section -->
<div class="relative isolate pt-14 h-full">
  <svg class="absolute inset-0 -z-10 h-full w-full stroke-gray-200 [mask-image:radial-gradient(100%_100%_at_top_right,white,transparent)]" aria-hidden="true">
    <defs>
      <pattern id="83fd4e5a-9d52-42fc-97b6-718e5d7ee527" width="200" height="200" x="50%" y="-1" patternUnits="userSpaceOnUse">
        <path d="M100 200V.5M.5 .5H200" fill="none" />
      </pattern>
    </defs>
    <svg x="50%" y="-1" class="overflow-visible fill-gray-50">
      <path d="M-100.5 0h201v201h-201Z M699.5 0h201v201h-201Z M499.5 400h201v201h-201Z M-300.5 600h201v201h-201Z" stroke-width="0" />
    </svg>
    <rect width="100%" height="100%" stroke-width="0" fill="url(#83fd4e5a-9d52-42fc-97b6-718e5d7ee527)" />
  </svg>
  <div class="mx-auto max-w-7xl px-6 py-16 h-full lg:flex lg:items-center lg:gap-x-10 lg:px-8 lg:py-20">
    <div class="mx-auto max-w-4xl lg:flex-auto text-center">
      <h1 class="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">
        Welcome to Event Management
      </h1>
      <p class="mt-6 text-lg leading-8 text-gray-600">
        A simple calendar event management application built with Ruby on Rails, StimulusJS, Hotwire and Tailwind CSS.
        We also used gem Administrate to provide a simple admin dashboard.
      </p>
      <div class="mt-10 flex justify-end items-center gap-x-6">
        <% if current_user.present? %>
          <%= link_to user_root_path, class: 'rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600' do %>
            Get started
          <% end %>
        <% else %>
          <%= link_to new_user_session_path, class: 'rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600' do %>
            Get started
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <% if content_for?(:title) %>
        <%= yield :title %> |
      <% end %>
      Calendar Event Management
    </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
  </head>

  <body data-controller="<%= controller.controller_name %>--<%= controller.action_name %>" class="h-full font-sans antialiased overflow-hidden font-normal leading-normal bg-white">
    <div class="flex min-h-full relative"
      data-controller="slideover"
      data-slideover-open-value="false"
      data-slideover-invisible-class="-translate-x-full,opacity-0"
      data-slideover-visible-class="translate-x-0,opacity-100"
      data-slideover-entering-class=""
      data-slideover-enter-timeout="300,300"
      data-slideover-leaving-class=""
      data-slideover-leave-timeout="300,0"
      data-slideover-active-target="#slideover-target"
    >
      <%= render partial: "shared/sidebar" %>

      <!-- Content area -->
      <div class="flex flex-1 flex-col overflow-hidden">
        <%= render partial: "shared/main_navbar" %>

        <%= render partial: "shared/flash" %>

        <!-- Main content -->
        <div class="h-full md:flex md:flex-1 sm:block md:items-stretch overflow-y-auto">
          <%= yield :content_sidebar %>

          <main class="w-full h-full flex-1">
            <%= yield %>
          </main>
        </div>
      </div>
    </div>

    <ninja-keys data-controller="command-palette" hideBreadcrumbs></ninja-keys>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <% if content_for?(:title) %>
        <%= yield :title %> |
      <% end %>
      Calendar Event Management
    </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
  </head>

  <body class="flex justify-between h-full font-sans antialiased font-normal leading-normal bg-white">
    <%= render partial: "shared/static_navbar" %>

    <main class="pt-14 w-full">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/static.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <% if content_for?(:title) %>
        <%= yield :title %> |
      <% end %>
      Calendar Event Management
    </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
  </head>

  <body class="flex justify-between h-full font-sans antialiased font-normal leading-normal bg-white">
    <%= render partial: "shared/static_navbar" %>

    <main class="w-full">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_flash.html.erb
<div id="flash">
  <% if notice %>
    <div data-controller="flash" class="alert alert-success shadow-md flex items-center fixed top-5 right-5 py-3 px-5 rounded-lg z-30" role="alert">
      <div class="flex items-center mr-4">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-4 mt-1 flex-shrink-0" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
        </svg>
        <p><%= sanitize notice %></p>
      </div>

      <button type="button" data-action="flash#dismiss">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
    </div>
  <% end %>

  <% if alert %>
    <div data-controller="flash" class="alert alert-warning flex items-center fixed top-5 right-5 py-3 px-5 rounded-lg z-30" role="alert">
      <div class="flex items-center mr-4">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clip-rule="evenodd" />
        </svg>
        <p><%= sanitize alert %></p>
      </div>

      <button type="button" data-action="flash#dismiss">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
    </div>
  <% end %>

  <% if flash[:error] %>
    <div data-controller="flash" class="alert alert-error flex items-center fixed top-5 right-5 py-3 px-5 rounded-lg z-30" role="alert">
      <div class="flex items-center mr-4">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clip-rule="evenodd" />
        </svg>
        <p><%= sanitize flash[:error] %></p>
      </div>

      <button type="button" data-action="flash#dismiss">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
    </div>
  <% end %>
</div>

app/views/shared/_main_navbar.html.erb
<nav class="flex flex-row items-center justify-between px-4 py-3 bg-white border-b border-gray-200 text-sm font-medium" data-controller="toggle">
  <div class="flex md:hidden pr-4">
    <button data-action="slideover#_show" type="button" class="border-r border-gray-200 text-gray-500 focus:outline-none lg:hidden">
      <span class="sr-only">Open sidebar</span>
      <!-- Heroicon name: outline/bars-3-bottom-left -->
      <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25H12" />
      </svg>
    </button>
  </div>

  <%= yield :page_title %>

  <div class="w-auto pb-0 ml-4 flex justify-end items-center" data-toggle-target="toggleable">

    <% if user_signed_in? %>
      <!-- Main menu -->
      <div class="inline-flex z-20 items-center leading-none text-gray-700 no-underline align-middle rounded hover:text-gray-800 hover:bg-white">
        <div class="relative" data-controller="dropdown">
          <div data-action="click->dropdown#toggle click@window->dropdown#hide touch->dropdown#toggle touch@window->dropdown#hide" role="button" class="inline-block select-none" aria-label="Profile Menu">
            <span class="flex items-center text-gray-700 appearance-none">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" class="w-4 h-4"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"></path></svg>
            </span>
          </div>
          <div data-dropdown-target="menu" class="z-20 hidden mt-2 absolute right-0 dropdown-menu">
            <div class="overflow-hidden bg-white border border-gray-200 rounded shadow-md">
              <%= link_to t("shared.navbar.profile"), edit_user_registration_path, class: 'no-underline block px-6 py-3 text-gray-800 bg-white hover:bg-primary-50 transition ease-in-out duration-200 whitespace-nowrap' %>
              <%= link_to t("shared.navbar.password"), account_password_path, class: 'no-underline block px-6 py-3 text-gray-800 bg-white  hover:bg-primary-50 transition ease-in-out duration-200 whitespace-nowrap' %>
              <%= button_to t("shared.navbar.sign_out"), destroy_user_session_path, method: :delete, class: 'w-full text-left font-medium cursor-pointer px-6 py-3 border-t border-gray-200 text-gray-800 bg-white hover:bg-primary-50 transition ease-in-out duration-200 whitespace-nowrap' %>
            </div>
          </div>
        </div>
      </div>
    <% else %>
      <%= link_to t("shared.navbar.log_in"), new_user_session_path, class: 'nav-link' %>
      <%= link_to t("shared.navbar.sign_up"), new_user_registration_path, class: 'btn btn-primary' %>
    <% end %>
  </div>
</nav>

app/views/shared/_menus.html.erb
<ul role="list" class="flex flex-1 flex-col gap-y-7 list-none h-full">
  <li>
    <ul role="list" class="-mx-2 space-y-1 list-none">
      <li>
        <a href="<%= root_path %>" class="<%= current_controller?("dashboards") ? "bg-gray-50 text-indigo-600" : "text-gray-700" %> text-gray-700 hover:text-indigo-600 hover:bg-gray-50 group flex gap-x-3 rounded-md p-2 text-sm leading-6 font-semibold" aria-current="page">
          <%= render_svg "icons/home", styles: "icon-sm #{current_controller?("dashboards") ? "text-indigo-600" : "text-gray-400"} group-hover:text-indigo-600 mr-4 flex-shrink-0 w-6 h-6" %>
          Dashboard
        </a>
      </li>
    </ul>
  </li>
</ul>

app/views/shared/_sidebar.html.erb
<div id="sidebar-mobile">
  <div data-slideover-target="overlay" data-action="click->slideover#_hide" class="fixed inset-0 flex z-40 transition-opacity ease-linear duration-300 opacity-0 hidden">
    <div class="fixed inset-0">
      <div class="absolute inset-0 bg-gray-600 opacity-75"></div>
    </div>
    <div id="slideover-target" data-slideover-target="menu" class="relative flex-1 flex flex-col max-w-xs w-full h-full pt-5 pb-4 bg-white transition ease-in-out duration-300 transform -translate-x-full hidden">
      <div class="absolute top-0 right-0 -mr-14 p-1">
        <button data-action="slideover#_hide" class="flex bg-gray-600 items-center justify-center h-12 w-12 rounded-full focus:outline-none focus:bg-gray-600" aria-label="Close sidebar">
          <span class="sr-only">Close sidebar</span>
          <%= render_svg "icons/x-mark", styles: "h-6 w-6 text-white" %>
        </button>
      </div>
      <div class="flex-shrink-0 flex items-center px-4">
        <h1 class="text-gray-900 text-2xl font-bold">Orealis Hub</h1>
      </div>
      <div class="mt-5 flex-1 h-0 overflow-y-auto">
        <nav class="px-2 flex flex-col justify-between">
          <%= render partial: "shared/menus" %>
        </nav>
      </div>
    </div>
    <div class="flex-shrink-0 w-14">
      <!-- Dummy element to force sidebar to shrink to fit close icon -->
    </div>
  </div>
</div>

<!-- Static sidebar for desktop -->
<div class="hidden bg-white w-44 lg:w-60 overflow-y-auto md:border-r md:border-gray-200 md:block">
  <!-- Sidebar component, swap this element with another sidebar if you like -->
  <div class="flex min-h-0 flex-1 flex-col h-full">
    <div class="flex flex-col h-16 flex-shrink-0 items-center justify-center px-4">
      <%= link_to root_path, class: "text-center" do %>
        <h1 class="text-gray-900 text-2xl font-bold">Orealis Hub</h1>
      <% end %>
    </div>
    <div class="flex flex-1 flex-col overflow-y-auto h-full">
      <nav class="flex-1 px-2 py-2 h-full">
        <%= render partial: "shared/menus" %>
      </nav>
    </div>
  </div>
</div>

app/views/shared/_static_navbar.html.erb
<header class="absolute inset-x-0 top-0 z-50">
  <nav class="flex items-center justify-between p-6 lg:px-8" aria-label="Global">
    <div class="flex lg:flex-1">
      <%= link_to root_path do %>
        <h1 class="text-gray-700 text-2xl font-bold">Event Management</h1>
      <% end %>
    </div>

    <div class="w-auto pb-0 ml-4 flex justify-end items-center" data-toggle-target="toggleable">
      <% if user_signed_in? %>
        <div class="inline-flex z-20 items-center leading-none text-gray-700 no-underline align-middle rounded hover:text-gray-800 hover:bg-white">
          <div class="relative">
            <div id="dropdownMenuIconHorizontalButton" data-dropdown-toggle="dropdownDotsHorizontal" class="inline-flex items-center p-2 text-sm font-medium text-center text-gray-900 bg-white rounded-full hover:bg-gray-100 focus:outline-none" type="button">
              <div class="relative w-8 h-8 overflow-hidden bg-gray-100 rounded-full dark:bg-gray-600">
                <svg class="absolute w-10 h-10 text-gray-400 -left-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"></path></svg>
              </div>
            </div>

            <!-- Dropdown menu -->
            <div id="dropdownDotsHorizontal" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-28">
              <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownMenuIconHorizontalButton">
                <li>
                  <%= link_to t("shared.navbar.profile"), edit_user_registration_path, class: 'block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white' %>
                </li>
                <li>
                  <%= button_to t("shared.navbar.sign_out"), destroy_user_session_path, method: :delete, class: 'block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white' %>
                </li>
              </ul>
            </div>
          </div>
        </div>
      <% else %>
        <%= link_to t("shared.navbar.log_in"), new_user_session_path, class: 'nav-link' %>
        <%= link_to t("shared.navbar.sign_up"), new_user_registration_path, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </nav>
</header>